---
- name: Delete Virtual Machine
  hosts: "{{ vm_host }}"
  vars:
    target_hostname: "{{ target_hostname }}"
  tasks:
    - name: Destroy VM
      become: true
      ansible.builtin.shell: virsh destroy {{ target_hostname }}
      ignore_errors: true

    - name: Undefine VM
      become: true
      ansible.builtin.shell: virsh undefine {{ target_hostname }} --remove-all-storage
      ignore_errors: true

    - name: Destroy Storage Pool
      become: true
      ansible.builtin.shell: virsh pool-destroy {{ target_hostname }}
      ignore_errors: true

    - name: Undefine Storage Pool
      become: true
      ansible.builtin.shell: virsh pool-undefine {{ target_hostname }}
      ignore_errors: true

    - name: Delete the directory
      become: true
      ansible.builtin.file:
        path: "/vms/{{ target_hostname }}"
        state: absent
      ignore_errors: true

    - name: Remove the VM from the inventory
      delegate_to: localhost
      ansible.builtin.lineinfile:
        path: "/etc/ansible/hosts"
        state: absent
        regexp: "^{{ target_hostname }}"
      ignore_errors: true

    - name: Remove the VM from the known_hosts file
      delegate_to: localhost
      ansible.builtin.shell: ssh-keygen -R {{ target_hostname }}
      ignore_errors: true