---
- name: Delete Virtual Machine
  hosts: "{{ vm_host }}"
  vars:
    target_hostname: "{{ target_hostname }}"
  tasks:
    - name: Destroy VM
      ansible.builtin.shell: virsh destroy {{ target_hostname }}
      ignore_errors: true

    - name: Undefine VM
      ansible.builtin.shell: virsh undefine {{ target_hostname }} --remove-all-storage
      ignore_errors: true

    - name: Delete the directory
      ansible.builtin.file:
        path: "/storage/vms/{{ target_hostname }}"
        state: absent
      ignore_errors: true
