- name: Scan all hosts
  hosts: "{{ target }}"
  tasks:
    - name: Write ansible host's host key to known hosts
      ansible.builtin.shell: "ssh-keyscan -H {{ item }} >> ~/.ssh/known_hosts"
      loop: "{{ groups['all'] }}"
      ignore_errors: true