---
- name: Prepare the Storage Server
  hosts: "{{ storage_server_hostname }}"
  become: true
  vars:
    subnet: "{{ subnet }}"
    lmod_version: "{{ lmod_version }}"
    admin_user: "{{ admin_user }}"
  tasks:
    ############################################################
    - name: Install dependencies
      ansible.builtin.apt:
        name:
          - libreadline-dev
          - nfs-kernel-server
          - bc
          - gcc
          - g++
          - gfortran
          - clang
          - gcc-10
          - g++-10
          - gfortran-10
          - gcc-12
          - g++-12
          - gfortran-12
          - lua5.3
          - lua-bit32:amd64
          - lua-posix:amd64
          - lua-posix-dev
          - liblua5.3-0:amd64
          - liblua5.3-dev:amd64
          - tcl
          - tcl-dev
          - tcl8.6
          - tcl8.6-dev:amd64
          - libtcl8.6:amd64
          - python3-pip
          - libpmix2
        state: present
        update_cache: yes

    ############################################################
    - name: Mount Points and environment management 
      become: true
      block:
        - name: Ensure groups exist with specific GIDs
          ansible.builtin.group:
            name: "{{ item.name }}"
            gid: "{{ item.gid }}"
            state: present
          loop:
            - { name: "slurm", gid: "1001" }
            - { name: "spack", gid: "1002" }
            - { name: "filemanager", gid: "1003" }
            - { name: "lmod", gid: "1004" }

        - name: Create users with home directories in /storage/home
          ansible.builtin.user:
            name: "{{ item.name }}"
            comment: "{{ item.comment }}"
            uid: "{{ item.uid }}"
            group: "{{ item.group }}"
            groups: "{{ item.groups }}"
            home: "{{ item.home }}"
            shell: /bin/bash
            createhome: yes
          loop:
            - { name: "slurm", comment: "Slurm User", uid: "1001", group: "slurm", groups: "", home: "/storage/home/slurm" }
            - { name: "spack", comment: "Software Manager User", uid: "1002", group: "spack", groups: "lmod", home: "/storage/spack"}
            - { name: "filemanager", comment: "File Manager User", uid: "1003", group: "filemanager", groups: "", home: "/storage/home/filemanager"}
            - { name: "lmod", comment: "lmod user", uid: "1004", group: "lmod", groups: "spack", home: "/home/lmod" }

        - name: Add admin account to groups
          ansible.builtin.user:
            name: "{{ admin_user }}"
            groups: "{{ item }}"
            append: true
          loop:
            - spack
            - filemanager
            - slurm
            - lmod

        - name: Create necessary directories
          ansible.builtin.file:
            path: "{{ item.path }}"
            state: directory
            owner: "{{ item.owner }}"
            group: "{{ item.group }}"
            mode: "{{ item.mode }}"
          loop:
            - { path: "/storage/home", owner: "filemanager", group: "filemanager", mode: "775" }
            - { path: "/storage/projects", owner: "filemanager", group: "filemanager", mode: "775" }
            - { path: "/storage/software", owner: "spack", group: "spack", mode: "775" }

    ############################################################
    - name: lmod
      become: true
      block:
        - name: Download and extract Lmod
          ansible.builtin.unarchive:
            src: "https://github.com/TACC/Lmod/archive/refs/tags/{{ lmod_version }}.tar.gz"
            dest: "/tmp"
            owner: lmod
            group: lmod
            remote_src: true

        - name: Install Lmod
          ansible.builtin.shell: |
            cd /tmp/Lmod-{{ lmod_version }}
            ./configure --prefix=/storage/software
            make install
          args:
            creates: "/storage/software/lmod"

        - name: Create symbolic link for Lmod profile script
          ansible.builtin.file:
            src: "/storage/software/lmod/lmod/init/profile"
            dest: /etc/profile.d/z00_lmod.sh
            state: link

        - name: Set MODULEPATH environment variable
          ansible.builtin.lineinfile:
            path: /etc/environment
            line: 'MODULEPATH="/storage/software/modules/linux-ubuntu22.04-x86_64/Core"'
            create: true

    ############################################################
    - name: Install Spack
      become: true
      block:
        - name: Check if Spack exists
          ansible.builtin.stat:
            path: /storage/spack/bin/spack
          register: spack_executable

        - name: Download and extract Spack
          ansible.builtin.unarchive:
            src: "https://github.com/spack/spack/archive/refs/tags/releases/latest.tar.gz"
            dest: "/tmp"
            remote_src: true
            owner: spack
            group: spack
          when: spack_executable.stat.exists == False

        - name: Move package to /storage/spack
          ansible.builtin.shell: mv /tmp/spack-releases-latest/* /storage/spack
          when: spack_executable.stat.exists == False

        - name: Modify Shell RC Configs
          ansible.builtin.lineinfile:
            path: "{{ item.path }}"
            line: source /storage/spack/share/spack/setup-env.sh
            create: yes
            state: present
          loop:
            - { path: "/storage/spack/.bashrc" }
            - { path: "/home/{{ admin_user }}/.bashrc" }
            - { path: "/home/{{ admin_user }}/.zshrc" }
          when: spack_executable.stat.exists == False

        - name: Set MODULEPATH for Lmod
          ansible.builtin.copy:
            dest: "/storage/software/lmod/lmod/init/.modulespath"
            content: "/storage/software/modules/linux-ubuntu22.04-x86_64/Core\n"
            owner: spack
            group: spack
            mode: '0740'
          when: spack_executable.stat.exists == False

        - name: Download config files
          ansible.builtin.get_url:
            url: https://raw.githubusercontent.com/gravityfargo/Virtual-HPC-Cluster/main/assets/spack/{{ item.file }}
            dest: "{{ item.dest }}"
          loop:
            - { file: "config.yaml", dest: "/storage/spack/etc/spack/config.yaml" }
            - { file: "compilers.yaml", dest: "/storage/spack/etc/spack/compilers.yaml" }
            - { file: "modules.yaml", dest: "/storage/spack/etc/spack/modules.yaml" }
          when: spack_executable.stat.exists == False

        - name: Change ownership 
          ansible.builtin.file:
            path: "{{ item.path }}"
            owner: "{{ item.owner }}"
            group: "{{ item.group }}"
            state: directory
            recurse: true
          loop:
            - { path: "/storage/projects", owner: "filemanager", group: "filemanager" }
            - { path: "/storage/software", owner: "spack", group: "spack" }
            - { path: "/storage/software/lmod", owner: "lmod", group: "lmod" }
            - { path: "/storage/spack", owner: "spack", group: "spack" }

        - name: Install Spack packages
          ansible.builtin.shell: /storage/spack/bin/spack install gmake
          become: true
          become_user: spack
          when: spack_executable.stat.exists == False
            
    ############################################################
    - name: NFS
      become: true
      block:
        - name: Enable NFS Kernel Server
          ansible.builtin.systemd:
            name: nfs-kernel-server
            enabled: yes
            state: started

        - name: Add NFS export entries to /etc/exports
          ansible.builtin.lineinfile:
            path: /etc/exports
            line: "/storage  {{ subnet }}(rw,sync,no_subtree_check)"
            create: yes

        - name: Apply NFS exports
          ansible.builtin.shell: exportfs -a