---
- name: Prepare the HPC Clients
  hosts: "{{ target_hostname }}"
  become: true
  vars:
    admin_user: "{{ admin_user }}"
    target_hostname: "{{ target_hostname }}"
    storage_server_hostname: "{{ storage_server_hostname }}"
  tasks:
    ############################################################
    - name: Install dependencies
      ansible.builtin.apt:
        name:
          - liblua5.3-dev
          - tcl-dev
          - libreadline-dev
          - nfs-kernel-server
          - bc
          - gcc
          - g++
          - gfortran
          - clang
          - gcc-10
          - g++-10
          - gfortran-10
          - gcc-12
          - g++-12
          - gfortran-12
        state: present
        update_cache: yes

    ############################################################
    - name: NFS Mount
      become: true
      block:

        - name: Ensure NFS mount is configured in /etc/fstab
          ansible.builtin.lineinfile:
            path: /etc/fstab
            line: "{{ storage_server_hostname }}:/storage /storage nfs defaults 0 0"
            state: present
            create: yes

        - name: Mount /storage if not already mounted
          ansible.builtin.mount:
            path: /storage
            src: "{{ storage_server_hostname }}:/storage"
            fstype: nfs
            opts: defaults
            state: mounted
          register: mount_status

    ############################################################
    - name: slurm, spack, and filemanager Users
      become: true
      block:

        - name: Ensure groups exist with specific GIDs
          ansible.builtin.group:
            name: "{{ item.name }}"
            gid: "{{ item.gid }}"
            state: present
          loop:
            - { name: "slurm", gid: "1001" }
            - { name: "spack", gid: "1002" }
            - { name: "filemanager", gid: "1003" }

        - name: Create users with home directories in /storage/home
          ansible.builtin.user:
            name: "{{ item.name }}"
            comment: "{{ item.comment }}"
            uid: "{{ item.uid }}"
            group: "{{ item.group }}"
            home: "{{ item.home }}"
            shell: /bin/bash
            createhome: no
          loop:
            - { name: "slurm", comment: "Slurm User", uid: "1001", group: "slurm", home: "/storage/home/slurm" }
            - { name: "spack", comment: "Software Manager User", uid: "1002", group: "spack", home: "/storage/spack"}
            - { name: "filemanager", comment: "File Manager User", uid: "1003", group: "filemanager", home: "/storage/home/filemanager"}

        - name: Add admin account to spack group
          ansible.builtin.user:
            name: "{{ admin_user }}"
            groups: "{{ item }}"
            append: true
          loop:
            - spack
            - filemanager
            - slurm
      when: mount_status is succeeded


    ############################################################
    - name: Lmod and Spack Environment Variables
      become: true
      block:

        - name: Create symbolic link for Lmod profile script
          ansible.builtin.file:
            src: "/storage/software/lmod/lmod/init/profile"
            dest: /etc/profile.d/z00_lmod.sh
            state: link

        - name: Set MODULEPATH environment variable
          ansible.builtin.lineinfile:
            path: /etc/environment
            line: 'MODULEPATH="/storage/software/modules/linux-ubuntu22.04-x86_64/Core"'
            create: true



