---
- name: Reset
  hosts: "{{ target_hostname }}"
  become: true
  vars:
    target_hostname: "{{ target_hostname }}"
    subnet: "{{ subnet }}"
  tasks:
    - name: Delete users
      ansible.builtin.user:
        name: "{{ item }}"
        state: absent
      loop:
        - slurm
        - spack
        - filemanager
        - lmod

    - name: Delete groups
      ansible.builtin.group:
        name: "{{ item }}"
        state: absent
      loop:
        - slurm
        - spack
        - filemanager
        - lmod

    - name: Remove contents of /storage
      ansible.builtin.shell: rm -rf /storage/*

    - name: lmod - remove profile script symbolic link
      ansible.builtin.file:
        path: /etc/profile.d/z00_lmod.sh
        state: absent

    - name: lmod - remove MODULEPATH environment variable setting
      ansible.builtin.lineinfile:
        path: /etc/environment
        line: 'MODULEPATH="/storage/software/modules/linux-ubuntu22.04-x86_64/Core"'
        state: absent

    - name: Storage Server - remove NFS exports
      ansible.builtin.lineinfile:
        path: /etc/exports
        line: "/storage  {{ subnet }}(rw,sync,no_subtree_check)"
        state: absent
      register: nfs_exports

    - name: Storage Server - Execute NFS exports
      ansible.builtin.shell: exportfs -a
      when: nfs_exports_change.changed
